name: RuboCop

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - uses: Swatinem/rust-cache@v2
    - run: cargo build --release

    - run: | 
        gem install rubocop
        gem install rubocop-minitest
        gem install rubocop-packaging
        gem install rubocop-performance
        gem install rubocop-rails

    - name: Run RuboCop
      run: time rubocop --parallel
      working-directory: rails

    - name: Run ruby-clippy
      run: time /home/runner/work/ruby-clippy/ruby-clippy/target/release/ruby-clippy
      working-directory: rails
